# Replica count for script runner & website
replicaCount: 1

resources:
  enabled: true
  cpu: 2
  memory: 2500Mi

# Images
image:
  repository: jupyter/datascience-notebook:python-3.9.6
  pullPolicy: IfNotPresent

# Service discovery for Website
service:
  type: ClusterIP
  targetPort: 8888
  protocol: TCP