apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Release.Name }}-service"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.targetPort }}{{ .Values.service.protocol | lower }}
      port: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: "{{ .Release.Name }}"
    release: {{ .Release.Name }}
