apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Release.Name }}-service"
spec:
  type: ClusterIP
  ports:
    - name: 8888tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: "{{ .Release.Name }}"
    release: {{ .Release.Name }}
