apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}-jupyter
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "{{ .Release.Name }}"
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        release: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        image: "jupyter/datascience-notebook:python-3.9.6"
        imagePullPolicy: "IfNotPresent"
        name: {{ .Release.Name }}-jupyter
        args:
        - /bin/bash
        - -c
        - 'cp -r /home/jovyan/work/.ssh /home/jovyan/ 2>/dev/null || : && jupyter lab --notebook-dir=/home/jovyan/work --ip 0.0.0.0 --no-browser --allow-root'
        ports:
        - containerPort: 8888
          name: 8888tcp
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 1000Mi
          limits:
            cpu: "{{ .Values.resources.cpu }}"
            memory: {{ .Values.resources.memory }}
