apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}-jupyter-{{ .Values.user }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "{{ .Release.Name }}"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
        release: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Values.user }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Release.Name }}-jupyter-{{ .Values.user }}
        args:
        - /bin/bash
        - -c
        - 'cp -r /home/jovyan/work/.ssh /home/jovyan/ 2>/dev/null || : && jupyter lab --notebook-dir=/home/jovyan/work --ip 0.0.0.0 --no-browser --allow-root'
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: {{ .Values.service.targetPort }}{{ .Values.service.protocol | lower }}
          protocol: {{ .Values.service.protocol }}
        resources:
          requests:
            cpu: "1"
            memory: 1000Mi
        {{- if .Values.resources.enabled }}
          limits:
            cpu: "{{ .Values.resources.cpu }}"
            memory: {{ .Values.resources.memory }}
        {{- end }}